### ISSUE TITLE
Radio buttons are not checked even the db has the data

### ISSUE THREAD

**Issue by mayeenulislam** [bamadesigner/manage-wordpress-posts-using-bulk-edit-and-quick-edit#2]
First of all thanks a lot :+1: for the awesome tutorial and git repo.

I can't make the radio button checked as per the checked data.

Here in your source, you can see that things're done gross.
https://github.com/bamadesigner/manage-wordpress-posts-using-bulk-edit-and-quick-edit/blob/master/bulk_quick_edit.js#L31-L35

I've checked with `console.log($( '#coming_soon-' + $post_id ).text());` with blank result.
Checked also with `console.log($( '#coming_soon-' + $post_id ).val());` with `undefined` result.

**Comment by mayeenulislam** [comment]
Ok, I solved it in a smart way I think using HTML5 `data` attribute

In my column (i.e. [your code](https://github.com/bamadesigner/manage-wordpress-posts-using-bulk-edit-and-quick-edit/blob/master/manage_wordpress_posts_using_bulk_edit_and_quick_edit.php#L174)) I did something like this:

```
  $cs = get_post_meta( $post_id, 'coming_soon', true );
  $icon_class = $cs === 'Yes' ? '<span class="dashicons dashicons-yes"></span>' : '';
  if( $cs ) {
      echo '<span data-cs="'. esc_js( $cs ) .'" id="coming_soon-' . $post_id . '">'. $icon_class .'</span>';
  }
```

And in [`.js` file](https://github.com/bamadesigner/manage-wordpress-posts-using-bulk-edit-and-quick-edit/blob/master/bulk_quick_edit.js#L32), I did this:

```
  var $coming_soon = $( '#coming_soon-' + $post_id ).data('cs');
```

Solved.
Thank you again for the nice tutorial that made me creating my first quick edit custom field. :+1:

**Comment by bamadesigner** [comment]
Glad you were able to sort it all out! Thanks!
